export type Lang = "en" | "pt" | "es";

export type Industry =
  | "financial-services"
  | "consumer-goods"
  | "pharma"
  | "healthcare-operations"
  | "enterprise-operations";

export type CaseSection = { heading: string; body: string };

export type CaseContent = {
  industryLabel: string;
  title: string;
  subtitle: string;
  shortDescription: string;
  tags: string[];
  sections: CaseSection[];
};

export type CaseRecord = {
  slug: string;
  industry: Industry;
  visual: "jj" | "nubank" | "bees" | "itau" | "contactCenter" | "branchResearch" | "marketplaceExpansion";
  heroAlt: string;
  hidden?: boolean;
  content: Record<Lang, CaseContent>;
};

const PLACEHOLDER = {
  en: "[Content coming soon]",
  pt: "[Conteúdo em breve]",
  es: "[Contenido próximamente]",
};

function sections(lang: Lang, overview: string, challenge: string, approach: string, solution: string, results: string): CaseSection[] {
  const labels = {
    en: ["Overview", "Challenge", "Approach", "Solution", "Results"],
    pt: ["Visão Geral", "Desafio", "Abordagem", "Solução", "Resultados"],
    es: ["Visión General", "Desafío", "Enfoque", "Solución", "Resultados"],
  }[lang];
  return [
    { heading: labels[0], body: overview },
    { heading: labels[1], body: challenge },
    { heading: labels[2], body: approach },
    { heading: labels[3], body: solution },
    { heading: labels[4], body: results },
  ];
}

const CC_EN = {
  overview: `A healthcare organization operated a complex Contact Center that handled multiple critical journeys related to treatment access, medical information and support for patients and healthcare professionals.\n\nThe Contact Center had significant inefficiencies that impacted handling time, quality of information provided, regulatory risk and operational cost. The operation relied heavily on manual processes, fragmented systems and tacit agent knowledge.\n\nThe project consisted of a complete strategic diagnosis: mapping processes, interviewing agents and leadership, analyzing tools and identifying improvement opportunities. More than 100 pain points were mapped across 8 main journeys, with impacts measured in rework, cost and regulatory risk.`,
  challenge: `The Contact Center operated as a central information hub for multiple audiences: patients seeking treatment access, healthcare professionals requesting technical information, and internal operations managing complex cases. Operational complexity generated critical problems:\n\n• Operational inefficiencies: manual-intensive processes, dependency on tacit knowledge, fragmented systems with no integration, outdated or inconsistent information across sources, lack of automation, constant rework.\n\n• Information gaps: agents without real-time access to updated information, need to consult multiple systems for simple queries, lack of unified interaction history, regulatory information not easily accessible, dependency on individual expertise.\n\n• Risk and compliance: high risk of outdated information delivery, difficulty tracing the origin of information provided, absence of clear audit trail, critical processes dependent on individual memory, regulatory exposure.\n\n• Business impact: high average handling time, low first-contact resolution, agent and customer dissatisfaction, high operational cost, difficulty scaling.`,
  approach: `The project was structured into 4 simultaneous workstreams over 8 weeks:\n\n1. Journey mapping (Service Design): 8 critical Contact Center journeys identified, end-to-end mapping of each flow (as-is), touchpoints, handoffs and dependencies, edge cases, operational workarounds documented.\n\n2. Deep qualitative research: interviews with 40+ agents across seniority levels, shadowing of real calls, interviews with leadership, conversations with adjacent areas (IT, compliance, operations), call recording and transcript analysis.\n\n3. Systems and tools analysis: audit of tools used by agents, integration mapping (or lack thereof), identification of sources of truth for critical information, log and operational data analysis, benchmarking of available technology.\n\n4. Prioritization and roadmap: 100+ pain points classified by impact and effort, regulatory risk analysis per opportunity, estimated impact on rework and cost, construction of an improvement roadmap, definition of quick wins vs. structural transformations.`,
  solution: `Complete documented diagnosis: 8 journeys mapped in detail (as-is), 100+ pain points identified and categorized, root cause analysis for main inefficiencies, impact quantification in time, cost and risk, documentation of missing critical processes.\n\nInformation gap map: identification of critical moments where agents lack necessary information, mapping of sources of truth (or lack of them), analysis of information update flows, automation opportunities for handoffs, prioritization of critical information for real-time availability.\n\nPrioritized improvement roadmap: quick wins (0–3 months) — simple automations and standardizations; structural improvements (3–9 months) — integrations and new tools; transformation (9–18 months) — evolution to autonomy and self-service; replicable prioritization framework.\n\nAutonomy framework: strategy to reduce dependency on tacit knowledge, proposal for a structured knowledge base, automation of information update flows, proactive alerts for agents, vision for self-service evolution.\n\nMapped automation opportunities: repetitive tasks identified for automation, proposed critical integrations between systems, automatic information update flows, proactive notifications, reduction of manual work in low-complexity cases.`,
  results: `Strategic clarity:\n• 100+ inefficiency points mapped and prioritized\n• 8 critical journeys documented for the first time\n• 18-month roadmap with impact-prioritized initiatives\n• Replicable framework for continuous opportunity analysis\n\nQuantified opportunities:\n• Estimated 40–50% reduction in average handling time through automation\n• Elimination of 60% of rework caused by information gaps\n• 35% reduction in regulatory risk through standardization of critical processes\n• Potential 30% reduction in operational cost via efficiency\n\nFoundation for transformation:\n• Consensus among leadership on priorities\n• Technical and business justification for investments\n• Clear evolution vision for the Contact Center\n• Alignment between operations, IT and compliance\n• Foundation for continuous improvement culture\n\nOrganizational impact:\n• Visibility over previously invisible critical dependencies\n• Agent engagement in the improvement process\n• Strategic alignment on the evolution of the operation\n• Evidence-based prioritization, not opinion\n• Clear roadmap for investment decisions`,
};

const CC_PT = {
  overview: `Uma organização de healthcare operava um Contact Center complexo que atendia múltiplas jornadas críticas relacionadas a acesso a tratamentos, informações médicas e suporte a pacientes e profissionais de saúde.\n\nO Contact Center apresentava ineficiências significativas que impactavam tempo de atendimento, qualidade da informação prestada, risco regulatório e custo operacional. A operação dependia fortemente de processos manuais, sistemas fragmentados e conhecimento tácito dos agentes.\n\nO projeto consistiu em um diagnóstico estratégico completo, mapeando processos, entrevistando agentes e lideranças, analisando ferramentas e identificando oportunidades de melhoria. Foram mapeados mais de 100 pontos de dor ao longo de 8 jornadas principais, com impactos mensurados em retrabalho, custo e risco regulatório.`,
  challenge: `O Contact Center operava como ponto central de informação para múltiplas audiências: pacientes buscando acesso a tratamentos, profissionais de saúde solicitando informações técnicas, e operações internas gerenciando casos complexos. A complexidade operacional gerava problemas críticos:\n\n• Ineficiências operacionais: processos manuais intensivos, dependência de conhecimento tácito, sistemas fragmentados sem integração, informações desatualizadas ou inconsistentes entre fontes, falta de automação, retrabalho constante.\n\n• Gaps de informação: agentes sem acesso a informações atualizadas em tempo real, necessidade de consultar múltiplos sistemas para responder dúvidas simples, falta de histórico unificado de interações, informações regulatórias críticas não facilmente acessíveis, dependência de expertise individual.\n\n• Risco e compliance: alto risco de fornecimento de informação desatualizada, dificuldade para rastrear origem de informações prestadas, ausência de trilha de auditoria clara, processos críticos dependentes de memória individual, exposição regulatória.\n\n• Impacto no negócio: tempo médio de atendimento elevado, baixa resolução de primeiro contato, insatisfação de agentes e clientes, custo operacional alto, dificuldade para escalar operação.`,
  approach: `O projeto foi estruturado em 4 frentes simultâneas ao longo de 8 semanas:\n\n1. Mapeamento de jornadas (Service Design): 8 jornadas críticas do Contact Center identificadas, mapeamento end-to-end de cada fluxo (as-is), touchpoints, handoffs e dependências, análise de exceções, documentação de workarounds operacionais.\n\n2. Pesquisa qualitativa profunda: entrevistas com 40+ agentes de diferentes níveis de senioridade, shadowing de atendimentos reais, entrevistas com lideranças e supervisores, conversas com áreas adjacentes (TI, compliance, operações), análise de gravações e transcrições.\n\n3. Análise de sistemas e ferramentas: auditoria de ferramentas utilizadas pelos agentes, mapeamento de integrações (ou falta delas), identificação de fontes de verdade para informações críticas, análise de logs e dados operacionais, benchmark de soluções disponíveis.\n\n4. Priorização e roadmap: classificação de 100+ pontos de dor por impacto e esforço, análise de risco regulatório por oportunidade, estimativa de impacto em retrabalho e custo, construção de roadmap de melhorias, definição de quick wins vs. transformações estruturais.`,
  solution: `Diagnóstico completo documentado: 8 jornadas mapeadas em detalhe (as-is), 100+ pontos de dor identificados e categorizados, análise de causa raiz para ineficiências principais, quantificação de impacto em tempo, custo e risco, documentação de processos críticos inexistentes.\n\nMapa de gaps de informação: identificação de momentos críticos onde agentes não têm informação necessária, mapeamento de fontes de verdade (ou falta delas), análise de fluxos de atualização de informação, identificação de oportunidades para automação de handoffs, priorização de informações críticas para disponibilização em tempo real.\n\nRoadmap priorizado de melhorias: quick wins (0–3 meses) — automações simples e padronizações; melhorias estruturais (3–9 meses) — integrações e novas ferramentas; transformação (9–18 meses) — evolução para autonomia e self-service; framework de priorização replicável.\n\nFramework de autonomia: estratégia para reduzir dependência de conhecimento tácito, proposta de base de conhecimento estruturada, automação de fluxos de atualização de informação, sistema de alertas proativos para agentes, visão de evolução para maior self-service.\n\nOportunidades de automação mapeadas: identificação de tarefas repetitivas passíveis de automação, proposta de integrações críticas entre sistemas, fluxos de atualização automática de informações, notificações proativas, redução de trabalho manual em casos de baixa complexidade.`,
  results: `Clareza estratégica:\n• 100+ pontos de ineficiência mapeados e priorizados\n• 8 jornadas críticas documentadas pela primeira vez\n• Roadmap de 18 meses com iniciativas priorizadas por impacto\n• Framework replicável para análise contínua de oportunidades\n\nOportunidades quantificadas:\n• Redução estimada de 40–50% no tempo médio de atendimento através de automações\n• Eliminação de 60% do retrabalho por falta de informação\n• Redução de 35% no risco regulatório por padronização de processos críticos\n• Potencial de 30% de redução de custo operacional via eficiência\n\nBase para transformação:\n• Consenso entre lideranças sobre prioridades\n• Justificativa técnica e de negócio para investimentos\n• Visão clara de evolução do Contact Center\n• Alinhamento entre operações, TI e compliance\n• Fundação para cultura de melhoria contínua\n\nImpacto organizacional:\n• Visibilidade sobre dependências críticas antes invisíveis\n• Engajamento de agentes no processo de melhoria\n• Alinhamento estratégico sobre evolução da operação\n• Priorização baseada em evidência, não opinião\n• Roadmap claro para decisões de investimento`,
};

const CC_ES = {
  overview: `Una organización de healthcare operaba un Contact Center complejo que atendía múltiples journeys críticos relacionados con acceso a tratamientos, información médica y soporte a pacientes y profesionales de la salud.\n\nEl Contact Center presentaba ineficiencias significativas que impactaban el tiempo de atención, la calidad de la información prestada, el riesgo regulatorio y el costo operacional. La operación dependía fuertemente de procesos manuales, sistemas fragmentados y conocimiento tácito de los agentes.\n\nEl proyecto consistió en un diagnóstico estratégico completo: mapeo de procesos, entrevistas con agentes y liderazgos, análisis de herramientas e identificación de oportunidades de mejora. Se mapearon más de 100 puntos de dolor a lo largo de 8 journeys principales, con impactos medidos en retrabajo, costo y riesgo regulatorio.`,
  challenge: `El Contact Center operaba como punto central de información para múltiples audiencias: pacientes buscando acceso a tratamientos, profesionales de la salud solicitando información técnica, y operaciones internas gestionando casos complejos. La complejidad operacional generaba problemas críticos:\n\n• Ineficiencias operacionales: procesos manuales intensivos, dependencia de conocimiento tácito, sistemas fragmentados sin integración, información desactualizada o inconsistente entre fuentes, falta de automatización, retrabajo constante.\n\n• Brechas de información: agentes sin acceso a información actualizada en tiempo real, necesidad de consultar múltiples sistemas para responder dudas simples, falta de historial unificado de interacciones, información regulatoria crítica no fácilmente accesible, dependencia de expertise individual.\n\n• Riesgo y compliance: alto riesgo de entrega de información desactualizada, dificultad para rastrear el origen de información prestada, ausencia de trazabilidad clara, procesos críticos dependientes de memoria individual, exposición regulatoria.\n\n• Impacto en el negocio: tiempo medio de atención elevado, baja resolución en primer contacto, insatisfacción de agentes y clientes, alto costo operacional, dificultad para escalar.`,
  approach: `El proyecto se estructuró en 4 frentes simultáneos durante 8 semanas:\n\n1. Mapeo de journeys (Service Design): 8 journeys críticos del Contact Center identificados, mapeo end-to-end de cada flujo (as-is), touchpoints, handoffs y dependencias, análisis de excepciones, documentación de workarounds operacionales.\n\n2. Investigación cualitativa profunda: entrevistas con 40+ agentes de diferentes niveles de seniority, shadowing de atenciones reales, entrevistas con liderazgos, conversaciones con áreas adyacentes (TI, compliance, operaciones), análisis de grabaciones y transcripciones.\n\n3. Análisis de sistemas y herramientas: auditoría de herramientas usadas por los agentes, mapeo de integraciones (o falta de ellas), identificación de fuentes de verdad para información crítica, análisis de logs y datos operacionales, benchmark de soluciones disponibles.\n\n4. Priorización y roadmap: clasificación de 100+ puntos de dolor por impacto y esfuerzo, análisis de riesgo regulatorio por oportunidad, estimación de impacto en retrabajo y costo, construcción de roadmap de mejoras, definición de quick wins vs. transformaciones estructurales.`,
  solution: `Diagnóstico completo documentado: 8 journeys mapeados en detalle (as-is), 100+ puntos de dolor identificados y categorizados, análisis de causa raíz para ineficiencias principales, cuantificación de impacto en tiempo, costo y riesgo, documentación de procesos críticos inexistentes.\n\nMapa de brechas de información: identificación de momentos críticos donde los agentes no tienen información necesaria, mapeo de fuentes de verdad (o falta de ellas), análisis de flujos de actualización de información, oportunidades de automatización de handoffs, priorización de información crítica para disponibilidad en tiempo real.\n\nRoadmap priorizado de mejoras: quick wins (0–3 meses) — automatizaciones simples y estandarizaciones; mejoras estructurales (3–9 meses) — integraciones y nuevas herramientas; transformación (9–18 meses) — evolución hacia autonomía y self-service; framework de priorización replicable.\n\nFramework de autonomía: estrategia para reducir la dependencia de conocimiento tácito, propuesta de base de conocimiento estructurada, automatización de flujos de actualización, sistema de alertas proactivas para agentes, visión de evolución hacia self-service.\n\nOportunidades de automatización mapeadas: identificación de tareas repetitivas pasibles de automatización, propuesta de integraciones críticas entre sistemas, flujos de actualización automática de información, notificaciones proactivas, reducción de trabajo manual en casos de baja complejidad.`,
  results: `Claridad estratégica:\n• 100+ puntos de ineficiencia mapeados y priorizados\n• 8 journeys críticos documentados por primera vez\n• Roadmap de 18 meses con iniciativas priorizadas por impacto\n• Framework replicable para análisis continuo de oportunidades\n\nOportunidades cuantificadas:\n• Reducción estimada de 40–50% en el tiempo medio de atención mediante automatización\n• Eliminación de 60% del retrabajo por falta de información\n• Reducción de 35% en el riesgo regulatorio por estandarización de procesos críticos\n• Potencial de 30% de reducción de costo operacional vía eficiencia\n\nBase para la transformación:\n• Consenso entre liderazgos sobre prioridades\n• Justificación técnica y de negocio para inversiones\n• Visión clara de evolución del Contact Center\n• Alineación entre operaciones, TI y compliance\n• Fundación para cultura de mejora continua\n\nImpacto organizacional:\n• Visibilidad sobre dependencias críticas antes invisibles\n• Compromiso de agentes en el proceso de mejora\n• Alineación estratégica sobre la evolución de la operación\n• Priorización basada en evidencia, no en opinión\n• Roadmap claro para decisiones de inversión`,
};

const BR_EN = {
  overview: `A large financial institution sought to deeply understand how the main banks in Brazil structured service for the elderly customer base at physical branches, considering different regional and cultural contexts.\n\nThe elderly customer base is critical for banks, especially on government benefit payment days when in-person service volume increases significantly. These customers have specific needs related to accessibility, communication clarity and in-person support.\n\nThe project combined deep desk research with on-site ethnographic visits to bank branches of multiple institutions during benefit payment days. The full physical journey, accessibility, space usage, communication strategies and queue management were analyzed.\n\nAs a result, we identified patterns, differentials and gaps in the current experience, plus 36 improvement opportunities to make service more accessible, efficient and aligned with this audience's needs.`,
  challenge: `Service for the elderly customer base at bank branches presented complex challenges that impacted both customer experience and banks' operational efficiency:\n\n• Concentration and volume: benefit payment days generated extreme demand peaks, long lines forming before branches even opened, volume concentrated in specific hours, difficulty sizing operations, impact on customers of other profiles.\n\n• 60+ audience needs: lower familiarity with digital and self-service channels, preference for in-person human service, specific physical accessibility needs, different information processing speed, greater need for guidance and support.\n\n• Accessibility barriers: physical infrastructure not always adequate (ramps, handrails, seating), complex visual communication or small fonts, lack of comfortable waiting areas, inaccessible or distant restrooms, absence of specific support for mobility limitations.\n\n• Pre-opening experience: customers arriving hours before opening time, outdoor lines without protection from sun/rain, lack of guidance on entry process, no early ticket distribution, discomfort and risk for vulnerable population.\n\n• Understanding gap: banks were unaware of the depth of frictions experienced, lack of systematic competitor benchmarking, unmapped improvement opportunities, no identified excellence standards, difficulty prioritizing investments.`,
  approach: `The project was structured into two complementary workstreams:\n\n1. Deep desk research: analysis of public policies for elderly service, accessibility regulations review, international benchmark of best practices, service-design innovation research for 60+ audience, demographic and behavioral data analysis.\n\n2. Field ethnographic research:\n\nStrategic planning: selection of 15+ branches from different banks, multiple Brazilian regions (considering distinct cultural contexts), focus on government benefit payment days, critical hours (pre-opening, opening, peak service).\n\nStructured observation: customer arrival (timing, formation of outdoor lines), pre-opening moment (how customers wait), branch opening (entry management, ticket distribution), full internal journey (reception, waiting, service, exit), interactions with staff and self-service systems.\n\nCritical dimensions analyzed: physical accessibility (ramps, handrails, doors, restrooms, seating); communication (signage, guidance, information clarity); queue management (ticketing systems, organization, waiting time); comfort (waiting areas, climate control, water availability); support (staff availability, guidance quality); space usage (layout, flows, dedicated 60+ areas).\n\nDocumentation: extensive photo records (respecting privacy), structured field notes, as-is journey mapping per bank, pattern and exception identification, comparative cross-institution analysis.`,
  solution: `Comparative benchmark between banks: 12+ experience criteria evaluation matrix, identification of best practices per dimension, competitive differentials analysis, common patterns and generalized gaps, performance scoring per institution.\n\n60+ oriented model: experience framework focused on specific needs, design principles for accessibility and clarity, adapted communication strategies, in-person support guidelines, peak-demand management on critical days.\n\n36 mapped improvement opportunities, grouped into 5 areas:\n\n• Pre-opening and arrival: early ticket distribution before opening, covered outdoor waiting areas, clear communication about hours and process, chairs and comfortable waiting support, staff guidance before opening.\n\n• Infrastructure and accessibility: ramp and handrail adequacy, comfortable seating in adequate quantity, accessible nearby restrooms, clear large-font signage, adequate lighting.\n\n• Service management: truly functional priority lines, simplified ticketing systems, dedicated service for simple operations, staff trained for empathetic support, simplified processes for recurring operations.\n\n• Communication and guidance: printed materials with large font and clear language, educational videos on self-service use, proactive staff guidance, disclosure of alternative channels, waiting time feedback.\n\n• Assisted digital experience: support for app usage, simplified self-service terminals, staff available to teach digital channel use, gradual assisted migration to reduce in-person demand.`,
  results: `Deep audience understanding:\n• 36 improvement opportunities identified and prioritized\n• Excellence patterns documented via benchmark\n• Critical experience gaps mapped\n• Regional contexts understood and considered\n• As-is journeys documented per bank and context\n\nIdentified competitive differentials:\n• Banks distributing tickets before opening reduced waiting time by 40%\n• Branches with dedicated 60+ areas received better evaluations\n• Proactive entry support improved welcome perception\n• Clear process communication reduced anxiety and confusion\n• Accessible infrastructure increased customer independence\n\nDecision-making foundation:\n• Investment prioritization based on real impact\n• Understanding of cost vs. experience trade-offs\n• Quick wins vs. structural improvements vision\n• Benchmark for continuous performance evaluation\n• Phased improvement roadmap\n\nOrganizational impact:\n• Internal awareness of audience reality\n• Alignment across areas (operations, facilities, service)\n• Systemic view of physical experience\n• Empathy and user-centered design culture\n• Replicable framework for future research\n\nStrategic opportunities:\n• Differentiation via superior 60+ experience\n• Operational cost reduction via assisted digital migration\n• NPS improvement in critical segment\n• Regulatory and reputational risk reduction\n• Brand strengthening via social responsibility`,
};

const BR_PT = {
  overview: `Uma instituição financeira de grande porte buscava compreender profundamente como os principais bancos do Brasil estruturavam o atendimento ao público aposentado em agências físicas, considerando diferentes contextos regionais e culturais.\n\nO público aposentado representa um segmento crítico para bancos, especialmente em dias de pagamento de benefícios governamentais, quando o volume de atendimentos presenciais aumenta significativamente. Esse público possui necessidades específicas relacionadas à acessibilidade, clareza de comunicação e suporte presencial.\n\nO projeto combinou desk research aprofundado com visitas presenciais etnográficas a agências bancárias de múltiplas instituições durante dias de pagamento de benefícios. Foram analisadas jornada física completa, acessibilidade, uso do espaço, estratégias de comunicação e gestão de filas.\n\nComo resultado, identificamos padrões, diferenciais e lacunas na experiência atual, além de 36 oportunidades de melhoria para tornar o atendimento mais acessível, eficiente e alinhado às necessidades desse público.`,
  challenge: `O atendimento ao público aposentado em agências bancárias apresentava desafios complexos que impactavam tanto a experiência dos clientes quanto a eficiência operacional dos bancos:\n\n• Concentração e volume: dias de pagamento de benefícios geravam picos extremos de demanda, filas extensas formadas antes mesmo da abertura das agências, volume concentrado em horários específicos, dificuldade para dimensionar operação adequadamente, impacto em clientes de outros perfis.\n\n• Necessidades específicas do público 60+: menor familiaridade com canais digitais e autoatendimento, preferência por atendimento humano presencial, necessidades específicas de acessibilidade física, velocidade de processamento de informação diferente, maior necessidade de orientação e suporte.\n\n• Barreiras de acessibilidade: infraestrutura física nem sempre adequada (rampas, corrimões, assentos), comunicação visual complexa ou com fonte pequena, falta de áreas de espera confortáveis, banheiros não acessíveis ou distantes, ausência de suporte específico para limitações de mobilidade.\n\n• Experiência pré-abertura: clientes chegando horas antes do horário de abertura, filas externas sem proteção contra sol/chuva, falta de orientação sobre processo de entrada, ausência de distribuição antecipada de senhas, desconforto e risco para população vulnerável.\n\n• Gap de compreensão: bancos desconheciam profundidade das fricções vividas, falta de benchmark sistemático entre concorrentes, oportunidades de melhoria não mapeadas, ausência de padrões de excelência identificados, dificuldade para priorizar investimentos.`,
  approach: `O projeto foi estruturado em duas frentes complementares:\n\n1. Desk research aprofundado: análise de políticas públicas de atendimento ao idoso, levantamento de regulamentações de acessibilidade, benchmark internacional de boas práticas, pesquisa de inovações em service design para público 60+, análise de dados demográficos e comportamentais.\n\n2. Pesquisa etnográfica em campo:\n\nPlanejamento estratégico: seleção de 15+ agências de diferentes bancos, múltiplas regiões do Brasil (considerando contextos culturais distintos), foco em dias de pagamento de benefícios governamentais, horários críticos (pré-abertura, abertura e pico de atendimento).\n\nObservação estruturada: chegada dos clientes (horários, formação de filas externas), momento de pré-abertura (como clientes aguardam), abertura da agência (gestão de entrada, distribuição de senhas), jornada interna completa (recepção, espera, atendimento, saída), interações com funcionários e sistemas de autoatendimento.\n\nAnálise de dimensões críticas: acessibilidade física (rampas, corrimões, portas, banheiros, assentos); comunicação (sinalização, orientação, clareza de informações); gestão de filas (sistema de senhas, organização, tempo de espera); conforto (áreas de espera, climatização, disponibilidade de água); suporte (disponibilidade de funcionários, qualidade de orientação); uso do espaço (layout, fluxos, áreas destinadas ao público 60+).\n\nDocumentação: registro fotográfico extensivo (respeitando privacidade), anotações de campo estruturadas, mapeamento de jornadas as-is por banco, identificação de padrões e exceções, análise comparativa entre instituições.`,
  solution: `Benchmark comparativo entre bancos: matriz de avaliação de 12+ critérios de experiência, identificação de melhores práticas por dimensão, análise de diferenciais competitivos, padrões comuns e lacunas generalizadas, scoring de performance por instituição.\n\nModelo orientado ao público 60+: framework de experiência focado em necessidades específicas, princípios de design para acessibilidade e clareza, estratégias de comunicação adaptadas, diretrizes de suporte presencial, gestão de picos de demanda em dias críticos.\n\n36 oportunidades de melhoria mapeadas, agrupadas em 5 áreas:\n\n• Pré-abertura e chegada: distribuição antecipada de senhas antes da abertura, áreas cobertas para espera externa, comunicação clara sobre horários e processo, cadeiras e suporte para espera confortável, orientação de funcionários antes da abertura.\n\n• Infraestrutura e acessibilidade: adequação de rampas e corrimões, assentos confortáveis e em quantidade adequada, banheiros acessíveis e próximos, sinalização clara e com fonte grande, iluminação adequada.\n\n• Gestão de atendimento: filas preferenciais realmente funcionais, sistema de senhas simplificado, atendimento dedicado para operações simples, funcionários treinados para suporte empático, processos simplificados para operações recorrentes.\n\n• Comunicação e orientação: materiais impressos com fonte grande e linguagem clara, vídeos educativos sobre uso de autoatendimento, orientação proativa de funcionários, canais alternativos de atendimento divulgados, feedback sobre tempo de espera.\n\n• Experiência digital assistida: suporte para uso de aplicativos, terminais de autoatendimento simplificados, funcionários disponíveis para ensinar uso de canais digitais, migração gradual e assistida para reduzir demanda presencial.`,
  results: `Compreensão profunda do público:\n• 36 oportunidades de melhoria identificadas e priorizadas\n• Padrões de excelência documentados via benchmark\n• Gaps críticos de experiência mapeados\n• Contextos regionais compreendidos e considerados\n• Jornadas as-is documentadas por banco e contexto\n\nDiferenciais competitivos identificados:\n• Bancos que distribuem senhas antes da abertura reduziram tempo de espera em 40%\n• Agências com áreas dedicadas ao público 60+ tiveram melhor avaliação\n• Suporte proativo na entrada melhorou percepção de acolhimento\n• Comunicação clara sobre processo reduziu ansiedade e confusão\n• Infraestrutura acessível aumentou independência dos clientes\n\nBase para tomada de decisão:\n• Priorização de investimentos baseada em impacto real\n• Compreensão de trade-offs entre custo e experiência\n• Visão de quick wins vs. melhorias estruturais\n• Benchmark para avaliação contínua de performance\n• Roadmap de melhorias com faseamento claro\n\nImpacto organizacional:\n• Sensibilização interna sobre realidade vivida pelo público\n• Alinhamento entre áreas (operações, facilities, atendimento)\n• Visão sistêmica de experiência física\n• Cultura de empatia e design centrado no usuário\n• Framework replicável para futuras pesquisas\n\nOportunidades estratégicas:\n• Diferenciação via experiência superior ao público 60+\n• Redução de custos operacionais via migração assistida para digital\n• Melhoria de NPS em segmento crítico\n• Redução de risco regulatório e reputacional\n• Fortalecimento de marca via responsabilidade social`,
};

const BR_ES = {
  overview: `Una institución financiera de gran porte buscaba comprender en profundidad cómo los principales bancos de Brasil estructuraban la atención al público jubilado en sucursales físicas, considerando diferentes contextos regionales y culturales.\n\nEl público jubilado representa un segmento crítico para los bancos, especialmente en días de pago de beneficios gubernamentales, cuando el volumen de atenciones presenciales aumenta significativamente. Este público posee necesidades específicas relacionadas con accesibilidad, claridad de comunicación y soporte presencial.\n\nEl proyecto combinó desk research profundo con visitas presenciales etnográficas a sucursales bancarias de múltiples instituciones durante días de pago de beneficios. Se analizó la jornada física completa, accesibilidad, uso del espacio, estrategias de comunicación y gestión de filas.\n\nComo resultado, identificamos patrones, diferenciales y brechas en la experiencia actual, además de 36 oportunidades de mejora para hacer la atención más accesible, eficiente y alineada a las necesidades de este público.`,
  challenge: `La atención al público jubilado en sucursales bancarias presentaba desafíos complejos que impactaban tanto la experiencia de los clientes como la eficiencia operacional de los bancos:\n\n• Concentración y volumen: los días de pago de beneficios generaban picos extremos de demanda, largas filas formadas antes incluso de la apertura, volumen concentrado en horarios específicos, dificultad para dimensionar la operación, impacto en clientes de otros perfiles.\n\n• Necesidades específicas del público 60+: menor familiaridad con canales digitales y autoservicio, preferencia por atención humana presencial, necesidades específicas de accesibilidad física, velocidad de procesamiento de información distinta, mayor necesidad de orientación y soporte.\n\n• Barreras de accesibilidad: infraestructura física no siempre adecuada (rampas, pasamanos, asientos), comunicación visual compleja o con fuente pequeña, falta de áreas de espera cómodas, baños no accesibles o distantes, ausencia de soporte específico para limitaciones de movilidad.\n\n• Experiencia pre-apertura: clientes llegando horas antes del horario de apertura, filas externas sin protección contra sol/lluvia, falta de orientación sobre el proceso de entrada, ausencia de distribución anticipada de tickets, incomodidad y riesgo para población vulnerable.\n\n• Brecha de comprensión: los bancos desconocían la profundidad de las fricciones vividas, falta de benchmark sistemático entre competidores, oportunidades de mejora no mapeadas, ausencia de estándares de excelencia identificados, dificultad para priorizar inversiones.`,
  approach: `El proyecto se estructuró en dos frentes complementarios:\n\n1. Desk research profundo: análisis de políticas públicas de atención al adulto mayor, revisión de regulaciones de accesibilidad, benchmark internacional de buenas prácticas, investigación de innovaciones en service design para público 60+, análisis de datos demográficos y comportamentales.\n\n2. Investigación etnográfica de campo:\n\nPlaneamiento estratégico: selección de 15+ sucursales de diferentes bancos, múltiples regiones de Brasil (considerando contextos culturales distintos), foco en días de pago de beneficios gubernamentales, horarios críticos (pre-apertura, apertura, pico de atención).\n\nObservación estructurada: llegada de los clientes (horarios, formación de filas externas), momento de pre-apertura (cómo los clientes esperan), apertura de la sucursal (gestión de entrada, distribución de tickets), jornada interna completa (recepción, espera, atención, salida), interacciones con personal y sistemas de autoservicio.\n\nDimensiones críticas analizadas: accesibilidad física (rampas, pasamanos, puertas, baños, asientos); comunicación (señalización, orientación, claridad de información); gestión de filas (sistema de tickets, organización, tiempo de espera); confort (áreas de espera, climatización, disponibilidad de agua); soporte (disponibilidad de personal, calidad de orientación); uso del espacio (layout, flujos, áreas dedicadas al público 60+).\n\nDocumentación: registro fotográfico extensivo (respetando privacidad), notas de campo estructuradas, mapeo de jornadas as-is por banco, identificación de patrones y excepciones, análisis comparativo entre instituciones.`,
  solution: `Benchmark comparativo entre bancos: matriz de evaluación de 12+ criterios de experiencia, identificación de mejores prácticas por dimensión, análisis de diferenciales competitivos, patrones comunes y brechas generalizadas, scoring de performance por institución.\n\nModelo orientado al público 60+: framework de experiencia enfocado en necesidades específicas, principios de diseño para accesibilidad y claridad, estrategias de comunicación adaptadas, directrices de soporte presencial, gestión de picos de demanda en días críticos.\n\n36 oportunidades de mejora mapeadas, agrupadas en 5 áreas:\n\n• Pre-apertura y llegada: distribución anticipada de tickets antes de la apertura, áreas cubiertas para espera externa, comunicación clara sobre horarios y proceso, sillas y soporte para espera cómoda, orientación de personal antes de la apertura.\n\n• Infraestructura y accesibilidad: adecuación de rampas y pasamanos, asientos cómodos y en cantidad adecuada, baños accesibles y cercanos, señalización clara y con fuente grande, iluminación adecuada.\n\n• Gestión de atención: filas preferenciales realmente funcionales, sistema de tickets simplificado, atención dedicada para operaciones simples, personal entrenado para soporte empático, procesos simplificados para operaciones recurrentes.\n\n• Comunicación y orientación: materiales impresos con fuente grande y lenguaje claro, videos educativos sobre uso de autoservicio, orientación proactiva del personal, canales alternativos de atención divulgados, feedback sobre tiempo de espera.\n\n• Experiencia digital asistida: soporte para uso de aplicaciones, terminales de autoservicio simplificados, personal disponible para enseñar el uso de canales digitales, migración gradual y asistida para reducir demanda presencial.`,
  results: `Comprensión profunda del público:\n• 36 oportunidades de mejora identificadas y priorizadas\n• Patrones de excelencia documentados vía benchmark\n• Brechas críticas de experiencia mapeadas\n• Contextos regionales comprendidos y considerados\n• Jornadas as-is documentadas por banco y contexto\n\nDiferenciales competitivos identificados:\n• Bancos que distribuyen tickets antes de la apertura redujeron el tiempo de espera en 40%\n• Sucursales con áreas dedicadas al público 60+ tuvieron mejor evaluación\n• Soporte proactivo en la entrada mejoró la percepción de acogida\n• Comunicación clara sobre el proceso redujo ansiedad y confusión\n• Infraestructura accesible aumentó la independencia de los clientes\n\nBase para la toma de decisiones:\n• Priorización de inversiones basada en impacto real\n• Comprensión de trade-offs entre costo y experiencia\n• Visión de quick wins vs. mejoras estructurales\n• Benchmark para evaluación continua de performance\n• Roadmap de mejoras con fases claras\n\nImpacto organizacional:\n• Sensibilización interna sobre realidad vivida por el público\n• Alineación entre áreas (operaciones, facilities, atención)\n• Visión sistémica de experiencia física\n• Cultura de empatía y diseño centrado en el usuario\n• Framework replicable para futuras investigaciones\n\nOportunidades estratégicas:\n• Diferenciación vía experiencia superior al público 60+\n• Reducción de costos operacionales vía migración asistida a digital\n• Mejora de NPS en segmento crítico\n• Reducción de riesgo regulatorio y reputacional\n• Fortalecimiento de marca vía responsabilidad social`,
};

const MP_EN = {
  overview: `A global consumer goods company operated a digital B2B marketplace connecting distributors and small retailers. With a consolidated presence in some markets, the company sought to expand into new territories with distinct cultural, economic and operational characteristics.\n\nInternational expansion of digital B2B platforms presents complex challenges: purchase behaviors vary drastically across countries, technology infrastructure is heterogeneous, commercial relationships have local dynamics and small retail digitalization is at different stages.\n\nThe project consisted of deep ethnographic research in three key markets: South Africa, South Korea and Turkey. In-person visits were made to small retailers, corner shops, spaza shops and wholesalers, plus interviews with owners, managers and sales representatives.\n\nAs a result, 39 opportunities were identified to optimize the platform according to regional dynamics, plus deep understanding of the role of wholesalers, purchase habits, inventory management and relationships with sales reps.`,
  challenge: `Expansion into new international markets required deep understanding of local contexts that could not be assumed from experiences in other countries:\n\n• Market diversity: South Africa — densely populated urban areas, strong informal commerce presence, spaza shops as community focal points, infrastructure challenges. South Korea — high digital penetration, mature market but with traditional B2B dynamics, high service expectations. Turkey — rapidly digitalizing market, strong personal relationship culture in business, wholesalers with central role.\n\n• Small retail complexity: store owner profiles varied drastically (age, education, digital maturity), heterogeneous business sizes (from corner shops to small supermarkets), informal inventory management without systems, purchasing decisions based on multiple local factors, relationships with wholesalers and sales reps as critical influencers.\n\n• Digitalization challenges: variable smartphone penetration, heterogeneous digital literacy, trust in digital platforms still being built, preference for human relationship vs. digital efficiency, different payment and logistics infrastructure.\n\n• Role of intermediaries: wholesalers as critical relationship gatekeepers, sales reps with advisory and support role, complex influence and decision-making dynamics, personal relationships as commercial assets, variable resistance or support to digitalization.\n\n• Knowledge gap: the company did not deeply understand local purchase habits, was unaware of market-specific frictions, assumed behaviors based on other countries, lacked clarity on feature priorities by region, did not know the real role of wholesalers in the purchase journey.`,
  approach: `Structured ethnographic research across three markets over 8 weeks:\n\n1. Strategic planning — site selection: South Africa (Johannesburg, Pretoria, Tembisa, Mamelodi, Hammanskraal, Mabopane, Atteridgeville); South Korea (Seoul, Busan, urban and peri-urban areas); Turkey (Istanbul, Ankara, dense commercial areas). Establishment profile: corner shops, spaza shops (informal township markets), urban mini-markets, small supermarkets, distributing wholesalers.\n\n2. Immersive field research — in-person visits: 30+ establishments visited across the three countries, on-site observation of daily operation, informal conversations with owners and managers, observation of interaction with end customers, photographic documentation of context.\n\nIn-depth interviews: small retail and corner shop owners, store managers, wholesalers and distributors, sales reps, end customers (when relevant).\n\nTopics explored: purchase and restocking habits; decision criteria (price, quality, relationship); inventory management; use of technology (apps, spreadsheets, paper); relationship with suppliers and wholesalers; daily operational challenges; perception of digital platforms; role of sales reps in the journey.\n\n3. Contextual analysis — demographics and profile: majority of owners under 35, average family size 3-5 people, densely populated areas (urban and peri-urban), strong informal commerce presence, community networks as business facilitators.\n\nInfrastructure and technology: smartphone penetration and connectivity, mobile data vs. Wi-Fi usage, app and e-commerce familiarity, available and preferred payment methods, logistics and delivery accessibility.\n\n4. Synthesis and prioritization: pattern and exception identification across markets, as-is purchase journey mapping by profile, comparative cross-country analysis, 39 improvement opportunities identified, prioritization by impact and feasibility per region.`,
  solution: `Deep understanding of 3 markets: detailed mapping of purchase behaviors, identification of cultural and operational particularities, analysis of barriers and enablers for digitalization, demographic and socioeconomic profile understanding, documentation of physical context and infrastructure.\n\n39 platform optimization opportunities, grouped into 5 areas:\n\n• Regional adaptation: feature personalization per market, culturally adequate language and communication, local payment methods, logistics adapted to infrastructure context, local-language support with cultural context.\n\n• Gradual digitalization: simplified onboarding for low digital maturity, hybrid human support (digital + phone/WhatsApp), platform usage education, progressive migration from offline to online channels, initial adoption incentives.\n\n• Relationship management: wholesalers as strategic partners, tools for sales reps, preservation of human relationship via platform, referral system and network effects, contextual support at critical moments.\n\n• Purchase experience: curated catalog by profile and region, history-based recommendations, easy reordering of recurring products, price and availability transparency, simplified order management.\n\n• Operation and logistics: delivery windows adapted to local context, data-supported inventory management, proactive notifications about critical products, integration with local wholesalers, support for basic financial management.\n\nReplicable expansion framework: structured ethnographic research methodology, new market evaluation criteria, regional adaptation playbook, success indicators per context, validation and iteration process.`,
  results: `Clarity on target markets:\n• 39 optimization opportunities identified and prioritized\n• 3 markets deeply understood\n• 30+ establishments visited and documented\n• Regional patterns mapped and validated\n• Replicable expansion framework for future markets\n\nCritical insights per market:\n\nSouth Africa: strong reliance on spaza shops as community hubs, informal trust networks as enablers, connectivity and infrastructure challenges, partnership opportunity with local wholesalers, growth potential in dense peri-urban areas.\n\nSouth Korea: high digital experience expectations, high technological maturity but traditional B2B processes, personal relationship still critical, differentiation opportunity via efficiency, demand for integration with existing systems.\n\nTurkey: rapidly digitalizing market, strong relationship culture in B2B business, wholesalers with central and influential role, strategic partnership opportunity with intermediaries, growth potential via education and support.\n\nFoundation for product decisions:\n• Feature prioritization per region\n• Evidence-based expansion roadmap\n• Culturally appropriate go-to-market strategy\n• Strategic partnerships identified per market\n• Support and operation model adapted\n\nOrganizational impact:\n• Strengthened research and empathy culture\n• Understanding of context diversity\n• Alignment between product, operations and expansion\n• Risk reduction in international launches\n• Replicable framework for future markets`,
};

const MP_PT = {
  overview: `Uma empresa global de consumer goods operava um marketplace B2B digital conectando distribuidores e pequenos varejistas. Com presença consolidada em alguns mercados, a empresa buscava expandir para novos territórios com características culturais, econômicas e operacionais distintas.\n\nA expansão internacional de plataformas digitais B2B apresenta desafios complexos: comportamentos de compra variam drasticamente entre países, infraestrutura tecnológica é heterogênea, relacionamentos comerciais têm dinâmicas locais e a digitalização do pequeno varejo está em estágios diferentes.\n\nO projeto consistiu em pesquisa etnográfica profunda em três mercados-chave: África do Sul, Coreia do Sul e Turquia. Foram realizadas visitas presenciais a pequenos mercados, corner shops, spaza shops e atacadistas, além de entrevistas com donos, gerentes e representantes de vendas.\n\nComo resultado, foram identificadas 39 oportunidades para otimizar a plataforma conforme dinâmicas regionais, além de compreensão profunda sobre papel de atacadistas, hábitos de compra, gestão de estoque e relacionamento com representantes de vendas.`,
  challenge: `A expansão para novos mercados internacionais exigia compreensão profunda de contextos locais que não poderiam ser assumidos a partir de experiências em outros países:\n\n• Diversidade de mercados: África do Sul — áreas urbanas densamente povoadas, forte presença de comércio informal, spaza shops como ponto focal de comunidades, desafios de infraestrutura. Coreia do Sul — alta penetração digital, mercado maduro mas com dinâmicas B2B tradicionais, expectativas elevadas de serviço. Turquia — mercado em rápida digitalização, forte cultura de relacionamento pessoal em negócios, atacadistas com papel central.\n\n• Complexidade do pequeno varejo: perfil dos donos de mercado variava drasticamente (idade, escolaridade, maturidade digital), tamanhos de negócio heterogêneos (desde corner shops até pequenos supermercados), gestão de estoque informal sem sistemas, decisões de compra baseadas em múltiplos fatores locais, relacionamento com atacadistas e representantes como influenciadores críticos.\n\n• Desafios de digitalização: penetração de smartphones variável entre mercados, alfabetização digital heterogênea, confiança em plataformas digitais em construção, preferência por relacionamento humano vs. eficiência digital, infraestrutura de pagamentos e logística diferentes.\n\n• Papel dos intermediários: atacadistas como gatekeepers críticos do relacionamento, representantes de vendas com papel de consultoria e suporte, dinâmica de influência e tomada de decisão complexa, relacionamentos pessoais como ativo comercial, resistência ou apoio à digitalização variável.\n\n• Gap de conhecimento: empresa não compreendia profundamente hábitos de compra locais, desconhecia fricções específicas de cada mercado, assumia comportamentos baseados em outros países, faltava clareza sobre prioridades de funcionalidades por região, desconhecia papel real de atacadistas na jornada de compra.`,
  approach: `Pesquisa etnográfica estruturada em três mercados ao longo de 8 semanas:\n\n1. Planejamento estratégico — seleção de locais: África do Sul (Johannesburg, Pretoria, Tembisa, Mamelodi, Hammanskraal, Mabopane, Atteridgeville); Coreia do Sul (Seul, Busan, áreas urbanas e peri-urbanas); Turquia (Istambul, Ankara, áreas comerciais densas). Perfil de estabelecimentos: corner shops, spaza shops (mercados informais em townships), mini-mercados urbanos, pequenos supermercados, atacadistas distribuidores.\n\n2. Pesquisa de campo imersiva — visitas presenciais: 30+ estabelecimentos visitados nos três países, observação in loco de operação diária, conversas informais com donos e gerentes, observação de interação com clientes finais, documentação fotográfica de contexto.\n\nEntrevistas em profundidade: donos de pequenos mercados e corner shops, gerentes de estabelecimentos, atacadistas e distribuidores, representantes de vendas, clientes finais (quando relevante).\n\nTópicos explorados: hábitos de compra e reposição de estoque; critérios de decisão (preço, qualidade, relacionamento); gestão de estoque e inventário; uso de tecnologia (apps, planilhas, papel); relacionamento com fornecedores e atacadistas; desafios operacionais do dia a dia; percepção de plataformas digitais; papel de representantes de vendas na jornada.\n\n3. Análise contextual — demografia e perfil: maioria de donos com menos de 35 anos, tamanho médio de família 3-5 pessoas, áreas densamente povoadas (urbanas e peri-urbanas), forte presença de comércio informal, redes comunitárias como facilitadoras de negócio.\n\nInfraestrutura e tecnologia: penetração de smartphones e conectividade, uso de mobile data vs. Wi-Fi, familiaridade com apps e e-commerce, métodos de pagamento disponíveis e preferidos, logística e acessibilidade de entregas.\n\n4. Síntese e priorização: identificação de padrões e exceções entre mercados, mapeamento de jornadas de compra as-is por perfil, análise comparativa entre países, identificação de 39 oportunidades de melhoria, priorização por impacto e viabilidade por região.`,
  solution: `Compreensão profunda de 3 mercados: mapeamento detalhado de comportamentos de compra, identificação de particularidades culturais e operacionais, análise de barreiras e facilitadores para digitalização, compreensão de perfil demográfico e socioeconômico, documentação de contexto físico e infraestrutura.\n\n39 oportunidades de otimização da plataforma, agrupadas em 5 áreas:\n\n• Adaptação regional: personalização de funcionalidades por mercado, linguagem e comunicação culturalmente adequadas, métodos de pagamento locais, logística adaptada a contexto de infraestrutura, suporte em idioma local com contexto cultural.\n\n• Digitalização gradual: onboarding simplificado para baixa maturidade digital, suporte humano híbrido (digital + telefone/WhatsApp), educação sobre uso da plataforma, migração progressiva de canais offline para online, incentivos para adoção inicial.\n\n• Gestão de relacionamentos: papel de atacadistas como parceiros estratégicos, ferramentas para representantes de vendas, preservação de relacionamento humano via plataforma, sistema de indicações e network effects, suporte contextual em momentos críticos.\n\n• Experiência de compra: catálogo curado por perfil e região, recomendações baseadas em histórico, facilidade de reposição de produtos recorrentes, transparência de preço e disponibilidade, gestão de pedidos simplificada.\n\n• Operação e logística: janelas de entrega adaptadas a contexto local, gestão de estoque apoiada por dados, notificações proativas sobre produtos críticos, integração com atacadistas locais, suporte para gestão financeira básica.\n\nFramework de expansão replicável: metodologia de pesquisa etnográfica estruturada, critérios de avaliação de novos mercados, playbook de adaptação regional, indicadores de sucesso por contexto, processo de validação e iteração.`,
  results: `Clareza sobre mercados-alvo:\n• 39 oportunidades de otimização identificadas e priorizadas\n• 3 mercados profundamente compreendidos\n• 30+ estabelecimentos visitados e documentados\n• Padrões regionais mapeados e validados\n• Framework de expansão replicável para futuros mercados\n\nInsights críticos por mercado:\n\nÁfrica do Sul: forte dependência de spaza shops como hubs comunitários, redes informais de confiança como facilitadoras, desafios de conectividade e infraestrutura, oportunidade de parceria com atacadistas locais, potencial de crescimento em áreas peri-urbanas densas.\n\nCoreia do Sul: expectativas elevadas de experiência digital, maturidade tecnológica alta mas processos B2B tradicionais, relacionamento pessoal ainda crítico, oportunidade de diferenciação via eficiência, demanda por integração com sistemas existentes.\n\nTurquia: mercado em rápida digitalização, forte cultura de relacionamento em negócios B2B, atacadistas com papel central e influente, oportunidade de parceria estratégica com intermediários, potencial de crescimento via educação e suporte.\n\nBase para decisões de produto:\n• Priorização de funcionalidades por região\n• Roadmap de expansão baseado em evidências\n• Estratégia de go-to-market culturalmente adequada\n• Parcerias estratégicas identificadas por mercado\n• Modelo de suporte e operação adaptado\n\nImpacto organizacional:\n• Cultura de pesquisa e empatia fortalecida\n• Compreensão de diversidade de contextos\n• Alinhamento entre produto, operações e expansão\n• Redução de risco em lançamentos internacionais\n• Framework replicável para futuros mercados`,
};

const MP_ES = {
  overview: `Una empresa global de consumer goods operaba un marketplace B2B digital conectando distribuidores y pequeños minoristas. Con presencia consolidada en algunos mercados, la empresa buscaba expandirse a nuevos territorios con características culturales, económicas y operacionales distintas.\n\nLa expansión internacional de plataformas digitales B2B presenta desafíos complejos: los comportamientos de compra varían drásticamente entre países, la infraestructura tecnológica es heterogénea, las relaciones comerciales tienen dinámicas locales y la digitalización del pequeño comercio está en distintas etapas.\n\nEl proyecto consistió en investigación etnográfica profunda en tres mercados clave: Sudáfrica, Corea del Sur y Turquía. Se realizaron visitas presenciales a pequeños comercios, corner shops, spaza shops y mayoristas, además de entrevistas con dueños, gerentes y representantes de ventas.\n\nComo resultado, se identificaron 39 oportunidades para optimizar la plataforma según dinámicas regionales, además de comprensión profunda sobre el rol de los mayoristas, hábitos de compra, gestión de inventario y relación con representantes de ventas.`,
  challenge: `La expansión a nuevos mercados internacionales exigía comprensión profunda de contextos locales que no podían asumirse a partir de experiencias en otros países:\n\n• Diversidad de mercados: Sudáfrica — áreas urbanas densamente pobladas, fuerte presencia de comercio informal, spaza shops como punto focal de comunidades, desafíos de infraestructura. Corea del Sur — alta penetración digital, mercado maduro pero con dinámicas B2B tradicionales, expectativas elevadas de servicio. Turquía — mercado en rápida digitalización, fuerte cultura de relación personal en los negocios, mayoristas con rol central.\n\n• Complejidad del pequeño comercio: perfil de los dueños variaba drásticamente (edad, escolaridad, madurez digital), tamaños de negocio heterogéneos (desde corner shops hasta pequeños supermercados), gestión de inventario informal sin sistemas, decisiones de compra basadas en múltiples factores locales, relación con mayoristas y representantes como influenciadores críticos.\n\n• Desafíos de digitalización: penetración variable de smartphones, alfabetización digital heterogénea, confianza en plataformas digitales en construcción, preferencia por relación humana vs. eficiencia digital, infraestructura de pagos y logística distintas.\n\n• Rol de los intermediarios: mayoristas como gatekeepers críticos de la relación, representantes de ventas con rol de consultoría y soporte, dinámica de influencia y toma de decisión compleja, relaciones personales como activo comercial, resistencia o apoyo a la digitalización variable.\n\n• Brecha de conocimiento: la empresa no comprendía en profundidad los hábitos de compra locales, desconocía fricciones específicas de cada mercado, asumía comportamientos basados en otros países, faltaba claridad sobre prioridades de funcionalidades por región, desconocía el rol real de los mayoristas en la jornada de compra.`,
  approach: `Investigación etnográfica estructurada en tres mercados durante 8 semanas:\n\n1. Planeamiento estratégico — selección de locales: Sudáfrica (Johannesburg, Pretoria, Tembisa, Mamelodi, Hammanskraal, Mabopane, Atteridgeville); Corea del Sur (Seúl, Busan, áreas urbanas y peri-urbanas); Turquía (Estambul, Ankara, áreas comerciales densas). Perfil de establecimientos: corner shops, spaza shops (comercios informales en townships), mini-mercados urbanos, pequeños supermercados, mayoristas distribuidores.\n\n2. Investigación de campo inmersiva — visitas presenciales: 30+ establecimientos visitados en los tres países, observación in loco de la operación diaria, conversaciones informales con dueños y gerentes, observación de interacción con clientes finales, documentación fotográfica de contexto.\n\nEntrevistas en profundidad: dueños de pequeños comercios y corner shops, gerentes de establecimientos, mayoristas y distribuidores, representantes de ventas, clientes finales (cuando fue relevante).\n\nTemas explorados: hábitos de compra y reposición de inventario; criterios de decisión (precio, calidad, relación); gestión de inventario; uso de tecnología (apps, planillas, papel); relación con proveedores y mayoristas; desafíos operacionales del día a día; percepción de plataformas digitales; rol de representantes de ventas en la jornada.\n\n3. Análisis contextual — demografía y perfil: mayoría de dueños menores de 35 años, tamaño medio de familia 3-5 personas, áreas densamente pobladas (urbanas y peri-urbanas), fuerte presencia de comercio informal, redes comunitarias como facilitadoras de negocio.\n\nInfraestructura y tecnología: penetración de smartphones y conectividad, uso de mobile data vs. Wi-Fi, familiaridad con apps y e-commerce, métodos de pago disponibles y preferidos, logística y accesibilidad de entregas.\n\n4. Síntesis y priorización: identificación de patrones y excepciones entre mercados, mapeo de jornadas de compra as-is por perfil, análisis comparativo entre países, identificación de 39 oportunidades de mejora, priorización por impacto y viabilidad por región.`,
  solution: `Comprensión profunda de 3 mercados: mapeo detallado de comportamientos de compra, identificación de particularidades culturales y operacionales, análisis de barreras y facilitadores para la digitalización, comprensión del perfil demográfico y socioeconómico, documentación del contexto físico e infraestructura.\n\n39 oportunidades de optimización de la plataforma, agrupadas en 5 áreas:\n\n• Adaptación regional: personalización de funcionalidades por mercado, lenguaje y comunicación culturalmente adecuados, métodos de pago locales, logística adaptada al contexto de infraestructura, soporte en idioma local con contexto cultural.\n\n• Digitalización gradual: onboarding simplificado para baja madurez digital, soporte humano híbrido (digital + teléfono/WhatsApp), educación sobre uso de la plataforma, migración progresiva de canales offline a online, incentivos para la adopción inicial.\n\n• Gestión de relaciones: rol de mayoristas como socios estratégicos, herramientas para representantes de ventas, preservación de la relación humana vía plataforma, sistema de referidos y network effects, soporte contextual en momentos críticos.\n\n• Experiencia de compra: catálogo curado por perfil y región, recomendaciones basadas en historial, facilidad de reposición de productos recurrentes, transparencia de precio y disponibilidad, gestión de pedidos simplificada.\n\n• Operación y logística: ventanas de entrega adaptadas al contexto local, gestión de inventario apoyada por datos, notificaciones proactivas sobre productos críticos, integración con mayoristas locales, soporte para gestión financiera básica.\n\nFramework de expansión replicable: metodología de investigación etnográfica estructurada, criterios de evaluación de nuevos mercados, playbook de adaptación regional, indicadores de éxito por contexto, proceso de validación e iteración.`,
  results: `Claridad sobre mercados objetivo:\n• 39 oportunidades de optimización identificadas y priorizadas\n• 3 mercados profundamente comprendidos\n• 30+ establecimientos visitados y documentados\n• Patrones regionales mapeados y validados\n• Framework de expansión replicable para futuros mercados\n\nInsights críticos por mercado:\n\nSudáfrica: fuerte dependencia de spaza shops como hubs comunitarios, redes informales de confianza como facilitadoras, desafíos de conectividad e infraestructura, oportunidad de alianza con mayoristas locales, potencial de crecimiento en áreas peri-urbanas densas.\n\nCorea del Sur: expectativas elevadas de experiencia digital, alta madurez tecnológica pero procesos B2B tradicionales, relación personal aún crítica, oportunidad de diferenciación vía eficiencia, demanda de integración con sistemas existentes.\n\nTurquía: mercado en rápida digitalización, fuerte cultura de relación en negocios B2B, mayoristas con rol central e influyente, oportunidad de alianza estratégica con intermediarios, potencial de crecimiento vía educación y soporte.\n\nBase para decisiones de producto:\n• Priorización de funcionalidades por región\n• Roadmap de expansión basado en evidencias\n• Estrategia de go-to-market culturalmente adecuada\n• Alianzas estratégicas identificadas por mercado\n• Modelo de soporte y operación adaptado\n\nImpacto organizacional:\n• Cultura de investigación y empatía fortalecida\n• Comprensión de la diversidad de contextos\n• Alineación entre producto, operaciones y expansión\n• Reducción de riesgo en lanzamientos internacionales\n• Framework replicable para futuros mercados`,
};

export const CASES: CaseRecord[] = [
  {
    slug: "contact-center-diagnostico",
    industry: "healthcare-operations",
    visual: "contactCenter",
    heroAlt: "Contact Center healthcare journey mapping and process optimization",
    hidden: true,
    content: {
      en: {
        industryLabel: "Healthcare Operations",
        title: "Strategic Contact Center Diagnosis: Efficiency, Risk and Improvement Prioritization",
        subtitle: "Healthcare | Contact Center Strategy | 2023",
        shortDescription: "Complete Contact Center diagnosis in healthcare identifying 100+ inefficiency points across 8 critical journeys. Process mapping, information gaps and prioritized improvements focused on automation and risk reduction.",
        tags: ["Service Design", "UX Research", "Operations Strategy", "Process Mapping"],
        sections: sections("en", CC_EN.overview, CC_EN.challenge, CC_EN.approach, CC_EN.solution, CC_EN.results),
      },
      pt: {
        industryLabel: "Healthcare Operations",
        title: "Diagnóstico Estratégico de Contact Center: Eficiência, Risco e Priorização de Melhorias",
        subtitle: "Healthcare | Contact Center Strategy | 2023",
        shortDescription: "Diagnóstico completo de Contact Center em healthcare identificando 100+ pontos de ineficiência em 8 jornadas críticas. Mapeamento de processos, gaps de informação e priorização de melhorias com foco em automação e redução de risco.",
        tags: ["Service Design", "UX Research", "Operations Strategy", "Process Mapping"],
        sections: sections("pt", CC_PT.overview, CC_PT.challenge, CC_PT.approach, CC_PT.solution, CC_PT.results),
      },
      es: {
        industryLabel: "Healthcare Operations",
        title: "Diagnóstico Estratégico de Contact Center: Eficiencia, Riesgo y Priorización de Mejoras",
        subtitle: "Healthcare | Contact Center Strategy | 2023",
        shortDescription: "Diagnóstico completo de Contact Center en healthcare identificando 100+ puntos de ineficiencia en 8 jornadas críticas. Mapeo de procesos, brechas de información y priorización de mejoras con foco en automatización y reducción de riesgo.",
        tags: ["Service Design", "UX Research", "Operations Strategy", "Process Mapping"],
        sections: sections("es", CC_ES.overview, CC_ES.challenge, CC_ES.approach, CC_ES.solution, CC_ES.results),
      },
    },
  },
  {
    slug: "agencias-aposentados-benchmark",
    industry: "financial-services",
    visual: "branchResearch",
    heroAlt: "Bank branch accessibility research for elderly customers",
    hidden: true,
    content: {
      en: {
        industryLabel: "Financial Services",
        title: "Elderly Customer Service Benchmark in Bank Branches",
        subtitle: "Financial Services | Service Design | 2023",
        shortDescription: "Ethnographic research in bank branches during benefit payment days. 36 improvement opportunities identified in accessibility, efficiency and experience for 60+ customers.",
        tags: ["UX Research", "Service Design", "Ethnographic Studies", "Accessibility"],
        sections: sections("en", BR_EN.overview, BR_EN.challenge, BR_EN.approach, BR_EN.solution, BR_EN.results),
      },
      pt: {
        industryLabel: "Serviços Financeiros",
        title: "Benchmark de Atendimento ao Público Aposentado em Agências Bancárias",
        subtitle: "Financial Services | Service Design | 2023",
        shortDescription: "Pesquisa etnográfica em agências bancárias durante dias de pagamento de benefícios. Identificadas 36 oportunidades de melhoria em acessibilidade, eficiência e experiência para público 60+.",
        tags: ["UX Research", "Service Design", "Ethnographic Studies", "Accessibility"],
        sections: sections("pt", BR_PT.overview, BR_PT.challenge, BR_PT.approach, BR_PT.solution, BR_PT.results),
      },
      es: {
        industryLabel: "Servicios Financieros",
        title: "Benchmark de Atención a Clientes Jubilados en Sucursales Bancarias",
        subtitle: "Financial Services | Service Design | 2023",
        shortDescription: "Investigación etnográfica en sucursales bancarias durante días de pago de beneficios. 36 oportunidades de mejora identificadas en accesibilidad y experiencia para público 60+.",
        tags: ["UX Research", "Service Design", "Ethnographic Studies", "Accessibility"],
        sections: sections("es", BR_ES.overview, BR_ES.challenge, BR_ES.approach, BR_ES.solution, BR_ES.results),
      },
    },
  },
  {
    slug: "marketplace-b2b-expansao-internacional",
    industry: "consumer-goods",
    visual: "marketplaceExpansion",
    heroAlt: "International B2B marketplace expansion research in emerging markets",
    content: {
      en: {
        industryLabel: "Consumer Goods",
        title: "Field research in consumer goods, around the world",
        subtitle: "Consumer Goods | International Expansion | 2023",
        shortDescription: "Ethnographic research across 3 emerging markets for B2B marketplace expansion. Deep understanding of small retailers, wholesalers and regional dynamics. 39 optimization opportunities identified.",
        tags: ["UX Research", "Ethnographic Studies", "Market Research", "Service Design"],
        sections: sections("en", MP_EN.overview, MP_EN.challenge, MP_EN.approach, MP_EN.solution, MP_EN.results),
      },
      pt: {
        industryLabel: "Bens de Consumo",
        title: "Pesquisa de campo em bens de consumo, no mundo todo",
        subtitle: "Consumer Goods | International Expansion | 2023",
        shortDescription: "Pesquisa etnográfica em 3 mercados emergentes para expansão de marketplace B2B. Compreensão profunda de donos de pequenos mercados, atacadistas e dinâmicas regionais. 39 oportunidades identificadas para otimização da plataforma.",
        tags: ["UX Research", "Ethnographic Studies", "Market Research", "Service Design"],
        sections: sections("pt", MP_PT.overview, MP_PT.challenge, MP_PT.approach, MP_PT.solution, MP_PT.results),
      },
      es: {
        industryLabel: "Bienes de Consumo",
        title: "Investigación de campo en bienes de consumo, en todo el mundo",
        subtitle: "Consumer Goods | International Expansion | 2023",
        shortDescription: "Investigación etnográfica en 3 mercados emergentes para expansión de marketplace B2B. Comprensión profunda de pequeños minoristas y dinámicas regionales. 39 oportunidades identificadas.",
        tags: ["UX Research", "Ethnographic Studies", "Market Research", "Service Design"],
        sections: sections("es", MP_ES.overview, MP_ES.challenge, MP_ES.approach, MP_ES.solution, MP_ES.results),
      },
    },
  },
];

export function getCaseBySlug(slug: string): CaseRecord | undefined {
  return CASES.find((c) => c.slug === slug);
}

export const UI = {
  en: {
    breadcrumbHome: "Home",
    breadcrumbCases: "Cases",
    listingTitle: "Cases",
    listingSubtitle: "Digital transformation, product strategy and experience projects",
    filterAll: "All",
    filterLabels: {
      "financial-services": "Financial Services",
      "consumer-goods": "Consumer Goods",
      "pharma": "Pharma",
      "healthcare-operations": "Healthcare Operations",
      "enterprise-operations": "Enterprise Operations",
    } as Record<Industry, string>,
    seeCase: "View full case",
    seeAll: "View all cases",
    backToCases: "← Back to cases",
    backToHome: "Go to home",
    ctaTitle: "Want results like these on your project?",
    ctaButton: "Talk to us",
    notFound: "Case not found.",
    metaListingTitle: "Cases | Sensorama Design",
    metaListingDesc: "Digital transformation, UX and product strategy projects for companies like Ambev, Itaú, Nubank and Johnson & Johnson.",
  },
  pt: {
    breadcrumbHome: "Home",
    breadcrumbCases: "Cases",
    listingTitle: "Cases",
    listingSubtitle: "Projetos de transformação digital, estratégia de produto e experiência",
    filterAll: "Todos",
    filterLabels: {
      "financial-services": "Serviços Financeiros",
      "consumer-goods": "Bens de Consumo",
      "pharma": "Farmacêutico",
      "healthcare-operations": "Healthcare Operations",
      "enterprise-operations": "Operações Empresariais",
    } as Record<Industry, string>,
    seeCase: "Acessar case completo",
    seeAll: "Todos os cases",
    backToCases: "← Voltar para cases",
    backToHome: "Ir para home",
    ctaTitle: "Quer resultados assim no seu projeto?",
    ctaButton: "Fale com a gente",
    notFound: "Case não encontrado.",
    metaListingTitle: "Cases | Sensorama Design",
    metaListingDesc: "Projetos de transformação digital, UX design e estratégia de produto para empresas como Ambev, Itaú, Nubank e Johnson & Johnson.",
  },
  es: {
    breadcrumbHome: "Home",
    breadcrumbCases: "Casos",
    listingTitle: "Casos",
    listingSubtitle: "Proyectos de transformación digital, estrategia de producto y experiencia",
    filterAll: "Todos",
    filterLabels: {
      "financial-services": "Servicios Financieros",
      "consumer-goods": "Bienes de Consumo",
      "pharma": "Farmacéutico",
      "healthcare-operations": "Healthcare Operations",
      "enterprise-operations": "Operaciones Empresariales",
    } as Record<Industry, string>,
    seeCase: "Ver caso completo",
    seeAll: "Ver todos los casos",
    backToCases: "← Volver a casos",
    backToHome: "Ir al inicio",
    ctaTitle: "¿Quieres resultados así en tu proyecto?",
    ctaButton: "Habla con nosotros",
    notFound: "Caso no encontrado.",
    metaListingTitle: "Casos | Sensorama Design",
    metaListingDesc: "Proyectos de transformación digital, UX y estrategia de producto para empresas como Ambev, Itaú, Nubank y Johnson & Johnson.",
  },
};

export const BASE_URL = "https://www.sensoramadesign.com";

export const langPath: Record<Lang, string> = { pt: "", en: "/en", es: "/es" };

export function casesPath(lang: Lang): string {
  return `${langPath[lang]}/cases`;
}

export function casePath(lang: Lang, slug: string): string {
  return `${langPath[lang]}/cases/${slug}`;
}

export function getAllCaseSlugs(): string[] {
  return CASES.filter((c) => !c.hidden).map((c) => c.slug);
}

export function getVisibleCases(): CaseRecord[] {
  return CASES.filter((c) => !c.hidden);
}

export function getCasesByIndustry(industry: Industry | "all"): CaseRecord[] {
  if (industry === "all") return getVisibleCases();
  return getVisibleCases().filter((c) => c.industry === industry);
}
